# -*- coding: utf-8 -*-
"""AI-Based Smart Traffic Congestion Detection and Analytics System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ozcoi9IOC5ApAswDiw1z7Kd2jjxh9FW8
"""

# CELL 1 — Force clean Pillow reinstall + ultralytics
import subprocess, sys

# Completely remove old Pillow and reinstall fresh
subprocess.run([sys.executable, "-m", "pip", "uninstall", "Pillow", "-y"], check=True)
subprocess.run([sys.executable, "-m", "pip", "install", "Pillow==10.4.0", "--no-cache-dir", "-q"], check=True)
subprocess.run([sys.executable, "-m", "pip", "install", "ultralytics", "opencv-python-headless", "pandas", "--no-cache-dir", "-q"], check=True)

print("✅ Packages installed. NOW go to Runtime → Restart session, then run from Cell 2.")

import cv2
import numpy as np
import pandas as pd
from ultralytics import YOLO
from collections import defaultdict
from google.colab import files
from IPython.display import display, HTML
import json, time, warnings
warnings.filterwarnings("ignore")
print("All imports OK")

model = YOLO("yolov8n.pt")

VEHICLE_CLASSES = {2: "car", 3: "motorcycle", 5: "bus", 7: "truck", 1: "bicycle"}
VEHICLE_WEIGHTS = {"car": 1.0, "motorcycle": 0.5, "bus": 2.5, "truck": 2.5, "bicycle": 0.3}
print("YOLOv8n loaded")

def congestion_level(vehicle_count, density_score, frame_area):

    # Better normalization
    density_ratio = density_score / max(frame_area, 1)

    # Weighted congestion score
    score = (
        vehicle_count * 3.5 +
        density_ratio * 180
    )

    # Clamp between 0 and 100
    score = max(0, min(score, 100))

    # Dynamic thresholds
    if score < 20:
        return "FREE FLOW", score, "#00e676"

    elif score < 40:
        return "LIGHT", score, "#76ff03"

    elif score < 60:
        return "MODERATE", score, "#ffea00"

    elif score < 80:
        return "HEAVY", score, "#ff6d00"

    else:
        return "SEVERE", score, "#d50000"

def time_period(frame_idx, total_frames):
    p = frame_idx / max(total_frames, 1)
    if p < 0.15:   return "Early Morning"
    elif p < 0.35: return "Morning Peak"
    elif p < 0.55: return "Midday"
    elif p < 0.75: return "Evening Peak"
    elif p < 0.90: return "Night"
    else:          return "Late Night"

STRATEGIES = {
    "FREE FLOW": ("Maintain current signal timings",
                  "Monitor for upstream build-up",
                  "Schedule maintenance in off-peak windows"),
    "LIGHT":     ("Minor signal optimisation recommended",
                  "Deploy variable message signs",
                  "Promote carpooling incentives"),
    "MODERATE":  ("Extend green phases by 15-20 s",
                  "Activate alternate route guidance",
                  "Evaluate additional turning lanes"),
    "HEAVY":     ("Activate adaptive signal control (SCOOT/SCATS)",
                  "Deploy traffic wardens; consider contraflow lanes",
                  "Introduce congestion pricing"),
    "SEVERE":    ("Emergency signal override - maximise throughput",
                  "Alert police; activate incident-management protocols",
                  "Urgent capacity expansion needed"),
}
print("Helper functions ready")

print("Upload your traffic video:")
uploaded = files.upload()
video_path = list(uploaded.keys())[0]
print(f"Uploaded: {video_path}")

cap = cv2.VideoCapture(video_path)
fps          = cap.get(cv2.CAP_PROP_FPS) or 25
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
width        = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height       = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
frame_area   = width * height
duration_sec = total_frames / fps
SAMPLE_EVERY = max(1, int(fps))

print(f"Video: {width}x{height} | {fps:.1f}fps | {total_frames} frames | {duration_sec:.1f}s")
print(f"Sampling 1 frame/sec => ~{total_frames // SAMPLE_EVERY} samples")

records, frame_idx, sampled = [], 0, 0
t0 = time.time()

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    if frame_idx % SAMPLE_EVERY == 0:
        res = model(frame, verbose=False, classes=list(VEHICLE_CLASSES.keys()))[0]
        counts, density = defaultdict(int), 0.0
        for box in res.boxes:
            cls_id = int(box.cls[0])
            if cls_id in VEHICLE_CLASSES:
                vtype = VEHICLE_CLASSES[cls_id]
                counts[vtype] += 1
                x1,y1,x2,y2 = box.xyxy[0].tolist()
                density += (x2-x1)*(y2-y1) * VEHICLE_WEIGHTS.get(vtype, 1.0)
        total_v = sum(counts.values())
        lvl, score, color = congestion_level(total_v, density, frame_area)
        records.append({
            "frame": frame_idx, "time_sec": frame_idx/fps,
            "total_vehicles": total_v, "cars": counts["car"],
            "buses": counts["bus"], "trucks": counts["truck"],
            "motorcycles": counts["motorcycle"], "bicycles": counts["bicycle"],
            "congestion_score": round(score, 2), "congestion_level": lvl,
            "time_period": time_period(frame_idx, total_frames),
        })
        sampled += 1
        if sampled % 5 == 0:
            pct = 100 * frame_idx / total_frames
            print(f"  {pct:.1f}% done | {sampled} samples | {time.time()-t0:.0f}s", end="\r")
    frame_idx += 1

cap.release()
df = pd.DataFrame(records)
print(f"\nDone! {len(df)} samples in {time.time()-t0:.1f}s")

peak_row      = df.loc[df["congestion_score"].idxmax()]
avg_score     = round(df["congestion_score"].mean(), 1)
avg_vehicles  = round(df["total_vehicles"].mean(), 1)
dominant      = df["congestion_level"].mode()[0]
level_order   = ["FREE FLOW","LIGHT","MODERATE","HEAVY","SEVERE"]
level_counts  = df["congestion_level"].value_counts().to_dict()
level_pcts    = {l: round(100*level_counts.get(l,0)/len(df), 1) for l in level_order}
vehicle_totals = {
    "Cars": int(df["cars"].sum()), "Buses": int(df["buses"].sum()),
    "Trucks": int(df["trucks"].sum()), "Motorcycles": int(df["motorcycles"].sum()),
    "Bicycles": int(df["bicycles"].sum()),
}
strat = STRATEGIES[dominant]
score_colors = {"FREE FLOW":"#00e676","LIGHT":"#76ff03","MODERATE":"#ffea00",
                "HEAVY":"#ff6d00","SEVERE":"#d50000"}
score_clr = score_colors[dominant]
period_df = (df.groupby("time_period")
               .agg(avg_score=("congestion_score","mean"),
                    avg_v=("total_vehicles","mean"),
                    peak=("congestion_level", lambda x: x.mode()[0]))
               .reset_index()
               .sort_values("avg_score", ascending=False))

print(f"Avg score: {avg_score}/100  |  Dominant: {dominant}")
print(period_df.to_string(index=False))

ts_labels   = [f"{r:.1f}s" for r in df["time_sec"].tolist()]
ts_scores   = df["congestion_score"].tolist()
ts_vehicles = df["total_vehicles"].tolist()

bar_vals    = [level_pcts[l] for l in level_order]
bar_colors  = ["#00c853", "#76ff03", "#ffea00", "#ff6d00", "#d50000"]

donut_lbls  = list(vehicle_totals.keys())
donut_vals  = list(vehicle_totals.values())
donut_clrs  = ["#2196F3", "#FF5722", "#9C27B0", "#FF9800", "#00BCD4"]

# Table rows
period_rows = ""
for _, row in period_df.iterrows():
    clr = score_colors.get(row["peak"], "#444")
    period_rows += (
        f'<tr>'
        f'<td>{row["time_period"]}</td>'
        f'<td>{row["avg_score"]:.1f}</td>'
        f'<td>{row["avg_v"]:.1f}</td>'
        f'<td><span class="badge" style="background:{clr};color:#fff">{row["peak"]}</span></td>'
        f'</tr>'
    )

# Gauge calculations
needle_angle = np.pi - np.pi * min(avg_score / 100, 1)
nx = round(100 + 75 * np.cos(needle_angle), 1)
ny = round(100 - 75 * np.sin(needle_angle), 1)
arc_offset = round(283 - 283 * min(avg_score / 100, 1), 1)

# JSON serialization
ts_labels_json   = json.dumps(ts_labels[:300])
ts_scores_json   = json.dumps(ts_scores[:300])
ts_vehicles_json = json.dumps(ts_vehicles[:300])

bar_vals_json    = json.dumps(bar_vals)
bar_colors_json  = json.dumps(bar_colors)

donut_lbls_json  = json.dumps(donut_lbls)
donut_vals_json  = json.dumps(donut_vals)
donut_clrs_json  = json.dumps(donut_clrs)

level_order_json = json.dumps(level_order)

css = """
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap');

*{
  margin:0;
  padding:0;
  box-sizing:border-box;
}

:root{
  --bg:#ffffff;
  --panel:#f7f7f7;
  --border:#e5e5e5;
  --text:#111111;
  --muted:#666666;
  --accent:#000000;
}

body{
  background:var(--bg);
  color:var(--text);
  font-family:'Inter',sans-serif;
  padding:24px;
}

.header{
  display:flex;
  justify-content:space-between;
  align-items:center;
  margin-bottom:28px;
  border-bottom:1px solid var(--border);
  padding-bottom:16px;
}

.header h1{
  font-size:1.4rem;
  font-weight:600;
  color:var(--accent);
}

.header .meta{
  font-size:.78rem;
  color:var(--muted);
  text-align:right;
  line-height:1.6;
}

.kpi-row{
  display:grid;
  grid-template-columns:repeat(auto-fit,minmax(180px,1fr));
  gap:14px;
  margin-bottom:20px;
}

.kpi{
  background:var(--panel);
  border:1px solid var(--border);
  border-radius:12px;
  padding:18px;
}

.kpi-label{
  font-size:.72rem;
  color:var(--muted);
  text-transform:uppercase;
  letter-spacing:.08em;
}

.kpi-value{
  font-size:1.8rem;
  font-weight:600;
  margin-top:8px;
}

.kpi-sub{
  font-size:.75rem;
  color:var(--muted);
  margin-top:4px;
}

.g2{
  display:grid;
  grid-template-columns:2fr 1fr;
  gap:16px;
  margin-bottom:20px;
}

.g2b{
  display:grid;
  grid-template-columns:1fr 1fr;
  gap:16px;
  margin-bottom:20px;
}

@media(max-width:768px){
  .g2,.g2b{
    grid-template-columns:1fr;
  }
}

.panel,
.gauge-wrap,
.period-wrap{
  background:var(--panel);
  border:1px solid var(--border);
  border-radius:12px;
  padding:20px;
}

.panel h3,
.period-wrap h3{
  font-size:.8rem;
  color:var(--muted);
  text-transform:uppercase;
  letter-spacing:.08em;
  margin-bottom:16px;
}

.gauge-wrap{
  display:flex;
  flex-direction:column;
  align-items:center;
}

.gauge-title{
  font-size:.75rem;
  color:var(--muted);
  margin-bottom:12px;
  text-transform:uppercase;
}

.gauge-val{
  font-size:2rem;
  font-weight:700;
  margin-top:10px;
}

.gauge-badge{
  margin-top:8px;
  padding:6px 16px;
  border-radius:30px;
  background:#1565C0;
  color:#fff;
  font-size:.72rem;
  font-weight:600;
}

.strat-item{
  display:flex;
  gap:12px;
  margin-bottom:14px;
}

.strat-icon{
  font-size:1.1rem;
}

.strat-tag{
  font-size:.7rem;
  color:var(--muted);
  text-transform:uppercase;
  margin-bottom:3px;
}

.strat-text{
  font-size:.86rem;
  line-height:1.5;
}

table{
  width:100%;
  border-collapse:collapse;
  font-size:.85rem;
}

th{
  text-align:left;
  padding-bottom:10px;
  color:var(--muted);
  border-bottom:1px solid var(--border);
}

td{
  padding:10px 4px;
  border-bottom:1px solid var(--border);
}

.badge{
  padding:4px 10px;
  border-radius:20px;
  font-size:.7rem;
  font-weight:600;
}

canvas{
  max-width:100%;
}
</style>
"""

html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">

<title>Traffic Dashboard</title>

<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>

{css}
</head>

<body>

<div class="header">
  <h1>Traffic Congestion Dashboard</h1>

  <div class="meta">
    YOLOv8n Detection<br>
    {len(df)} Samples | {duration_sec:.1f}s Video<br>
    Resolution: {width} × {height}
  </div>
</div>

<div class="kpi-row">

  <div class="kpi">
    <div class="kpi-label">Average Score</div>
    <div class="kpi-value">{avg_score}/100</div>
    <div class="kpi-sub">Road congestion intensity</div>
  </div>

  <div class="kpi">
    <div class="kpi-label">Dominant Level</div>
    <div class="kpi-value" style="font-size:1.2rem">{dominant}</div>
    <div class="kpi-sub">{level_pcts[dominant]}% of duration</div>
  </div>

  <div class="kpi">
    <div class="kpi-label">Peak Vehicles</div>
    <div class="kpi-value">{int(peak_row['total_vehicles'])}</div>
    <div class="kpi-sub">at {peak_row['time_sec']:.1f}s</div>
  </div>

  <div class="kpi">
    <div class="kpi-label">Average Vehicles</div>
    <div class="kpi-value">{avg_vehicles}</div>
    <div class="kpi-sub">Per sampled frame</div>
  </div>

  <div class="kpi">
    <div class="kpi-label">Total Cars</div>
    <div class="kpi-value">{vehicle_totals['Cars']:,}</div>
    <div class="kpi-sub">
      + {sum(v for k,v in vehicle_totals.items() if k!='Cars'):,} other vehicles
    </div>
  </div>

</div>

<div class="g2">

  <div class="panel">
    <h3>Congestion Score Timeline</h3>
    <canvas id="tsChart" height="90"></canvas>
  </div>

  <div class="gauge-wrap">

    <div class="gauge-title">Overall Congestion</div>

    <div class="gauge-arc">
      <svg viewBox="0 0 200 100">

        <path d="M 10 100 A 90 90 0 0 1 190 100"
              fill="none"
              stroke="#ddd"
              stroke-width="14"
              stroke-linecap="round"/>

        <path d="M 10 100 A 90 90 0 0 1 190 100"
              fill="none"
              stroke="#1565C0"
              stroke-width="14"
              stroke-linecap="round"
              stroke-dasharray="283"
              stroke-dashoffset="{arc_offset}"/>

        <line x1="100" y1="100"
              x2="{nx}" y2="{ny}"
              stroke="#1565C0"
              stroke-width="3"/>

        <circle cx="100" cy="100" r="5" fill="#1565C0"/>

      </svg>
    </div>

    <div class="gauge-val">{avg_score}/100</div>
    <div class="gauge-badge">{dominant}</div>

  </div>

</div>

<div class="g2">

  <div class="panel">
    <h3>Congestion Distribution</h3>
    <canvas id="barChart" height="70"></canvas>
  </div>

  <div class="panel">
    <h3>Vehicle Composition</h3>
    <canvas id="donutChart" height="130"></canvas>
  </div>

</div>

<div class="g2b">

  <div class="panel">

    <h3>Mitigation Strategies</h3>

    <div class="strat-item">
      <div class="strat-icon">⚡</div>
      <div>
        <div class="strat-tag">Immediate</div>
        <div class="strat-text">{strat[0]}</div>
      </div>
    </div>

    <div class="strat-item">
      <div class="strat-icon">🔄</div>
      <div>
        <div class="strat-tag">Short-Term</div>
        <div class="strat-text">{strat[1]}</div>
      </div>
    </div>

    <div class="strat-item">
      <div class="strat-icon">🏗</div>
      <div>
        <div class="strat-tag">Long-Term</div>
        <div class="strat-text">{strat[2]}</div>
      </div>
    </div>

  </div>

  <div class="panel">
    <h3>Vehicle Count Timeline</h3>
    <canvas id="vcChart" height="120"></canvas>
  </div>

</div>

<div class="period-wrap">

  <h3>Time Period Breakdown</h3>

  <table>
    <thead>
      <tr>
        <th>Period</th>
        <th>Avg Score</th>
        <th>Avg Vehicles</th>
        <th>Peak Level</th>
      </tr>
    </thead>

    <tbody>
      {period_rows}
    </tbody>
  </table>

</div>

<script>

const C = (id) => document.getElementById(id).getContext('2d');

const baseOpts = {{
  responsive:true,
  plugins:{{
    legend:{{
      labels:{{
        color:'#444'
      }}
    }}
  }}
}};

new Chart(C('tsChart'), {{
  type:'line',
  data:{{
    labels:{ts_labels_json},
    datasets:[{{
      label:'Congestion Score',
      data:{ts_scores_json},
      borderColor:'#1565C0',
      backgroundColor:'rgba(21,101,192,0.08)',
      fill:true,
      pointRadius:0,
      tension:0.4
    }}]
  }},
  options:{{
    ...baseOpts
  }}
}});

new Chart(C('barChart'), {{
  type:'bar',
  data:{{
    labels:{level_order_json},
    datasets:[{{
      data:{bar_vals_json},
      backgroundColor:{bar_colors_json},
      borderRadius:4
    }}]
  }},
  options:{{
    ...baseOpts
  }}
}});

new Chart(C('donutChart'), {{
  type:'doughnut',
  data:{{
    labels:{donut_lbls_json},
    datasets:[{{
      data:{donut_vals_json},
      backgroundColor:{donut_clrs_json},
      borderWidth:2
    }}]
  }},
  options:{{
    ...baseOpts,
    cutout:'68%'
  }}
}});

new Chart(C('vcChart'), {{
  type:'bar',
  data:{{
    labels:{ts_labels_json},
    datasets:[{{
      label:'Vehicles',
      data:{ts_vehicles_json},
      backgroundColor:'#43A047'
    }}]
  }},
  options:{{
    ...baseOpts
  }}
}});

</script>

</body>
</html>
"""

with open("traffic_dashboard.html", "w") as f:
    f.write(html)

print("Minimalist dashboard saved successfully!")

display(HTML(f'<div style="height:900px;overflow:auto">{html}</div>'))

df.to_csv("traffic_report.csv", index=False)
files.download("traffic_dashboard.html")
files.download("traffic_report.csv")
print("Downloaded!")

# ─── CELL 10 (Optional): Annotated video export ─────────────
cap    = cv2.VideoCapture(video_path)
fourcc = cv2.VideoWriter_fourcc(*"mp4v")
out    = cv2.VideoWriter("annotated.mp4", fourcc, fps, (width, height))
BGR    = {"FREE FLOW":(0,230,118),"LIGHT":(3,255,118),
          "MODERATE":(0,234,255),"HEAVY":(0,109,255),"SEVERE":(0,0,213)}
smap   = dict(zip(df["frame"], zip(df["congestion_level"],
                                    df["congestion_score"],
                                    df["total_vehicles"])))
frame_idx  = 0
last_lvl   = "FREE FLOW"
last_score = 0
last_count = 0

while cap.isOpened():
    ret, frame = cap.read()
    if not ret: break
    if frame_idx in smap:
        last_lvl, last_score, last_count = smap[frame_idx]
    bgr = BGR.get(last_lvl,(255,255,255))
    ov  = frame.copy()
    cv2.rectangle(ov,(0,0),(width,52),(8,15,30),-1)
    cv2.addWeighted(ov,0.75,frame,0.25,0,frame)
    cv2.putText(frame,f"CONGESTION: {last_lvl}",(12,32),
                cv2.FONT_HERSHEY_SIMPLEX,0.7,bgr,2,cv2.LINE_AA)
    cv2.putText(frame,f"Score:{last_score:.0f}/100  Vehicles:{int(last_count)}",
                (360,32),cv2.FONT_HERSHEY_SIMPLEX,0.52,(200,220,240),1,cv2.LINE_AA)
    bw = int((width-24)*min(last_score/100,1))
    cv2.rectangle(frame,(12,42),(width-12,50),(20,30,50),-1)
    cv2.rectangle(frame,(12,42),(12+bw,50),bgr,-1)
    out.write(frame)
    frame_idx += 1
    if frame_idx % 100 == 0:
        print(f"  {100*frame_idx/total_frames:.1f}%", end="\r")

cap.release(); out.release()
print("\nAnnotated video saved!")
files.download("annotated.mp4")